/control/verbose 2
/tracking/verbose 0
/process/optical/verbose 1
/run/verbose 1
/control/cout/ignoreThreadsExcept 0

# ----------------------------
# Materials
# ----------------------------

/opnovice2/boxMaterial G4_PLASTIC_SC_VINYLTOLUENE
/opnovice2/worldMaterial G4_AIR


# ----------------------------
# EJ-200 (Box) Property
# ----------------------------

# Light output (% Anthracene): 64
# ...

# Scintillation efficiency (photons / 1 MeV e-): 10000
/opnovice2/boxConstProperty SCINTILLATIONYIELD 10000/MeV
/opnovice2/boxConstProperty SCINTILLATIONYIELD1 1.0
/opnovice2/boxConstProperty RESOLUTIONSCALE 1.0

# Wavelength of Maximum Emission (nm): 425
# The data points are taken from EJ-200 emission sheet.
/opnovice2/boxProperty SCINTILLATIONCOMPONENT1 2.4982*eV 0.069 2.5419*eV 0.109 2.5623*eV 0.134 2.5838*eV 0.174 2.6039*eV 0.214 2.6273*eV 0.274 2.6495*eV 0.335 2.6823*eV 0.415 2.7196*eV 0.468 2.7700*eV 0.582 2.8458*eV 0.851 2.9033*eV 0.991 2.9173*eV 1.000 2.9313*eV 0.985 2.9383*eV 0.960 2.9516*eV 0.881 3.0092*eV 0.352 3.1001*eV 0.017

# Light Attenuation Length (cm): 380
# The energy range is set to accomodate 380nm~600nm (see EJ-200 emission spectrum)
/opnovice2/boxProperty ABSLENGTH 2.0*eV 380*cm 3.3*eV 380*cm

# Rise Time (ns): 0.9
/opnovice2/boxConstProperty SCINTILLATIONRISETIME1 0.9*ns

# Decay Time (ns): 2.1
/opnovice2/boxConstProperty SCINTILLATIONTIMECONSTANT1 2.1*ns

# Pulse Width, FWHM (ns): 2.5
# ...

# Density (g / cm3): 1.023
# ...

# Refractive Index: 1.58
/opnovice2/boxProperty RINDEX 2.0*eV 1.58 3.3*eV 1.58

# ----------------------------
# World Properties
# ----------------------------

/opnovice2/worldProperty RINDEX 2*eV 1.0003 3.3*eV 1.0003

# ----------------------------
# Surface / boundary behavior
# First version: scintillator-air dielectric interface
# ----------------------------

/opnovice2/surfaceModel unified
/opnovice2/surfaceType dielectric_dielectric
/opnovice2/surfaceFinish polished
/opnovice2/surfaceSigmaAlpha 0.0

# ----------------------------
# Optical processes
# ----------------------------

/process/optical/processActivation Cerenkov false
/process/optical/processActivation Scintillation true       # The EJ-200 emits photons
/process/optical/processActivation OpAbsorption true        # The EJ-200 has absorption length
/process/optical/processActivation OpBoundary true          # We need to do boundary processes
/process/optical/processActivation OpRayleigh false
/process/optical/processActivation OpMieHG false
/process/optical/processActivation OpWLS false

/process/optical/scintillation/setByParticleType false
/process/optical/scintillation/setTrackInfo false
/process/optical/scintillation/setFiniteRiseTime true           # The EJ-200 has a rise time
/process/optical/scintillation/setStackPhotons true
/process/optical/scintillation/setTrackSecondariesFirst true

# ----------------------------
# Initialize
# ----------------------------
/run/initialize

# ROOT output
/analysis/setFileName ej200_electron_boundary

# histograms
/analysis/h1/set 2 100 2.0 3.5  # scintillation spectrum [eV]
/analysis/h1/set 3 400 0 100    # scintillation time [ns]
/analysis/h1/set 10 40 -1 39    # boundary status
/analysis/h1/set 20 100 0 90    # Fresnel refraction angle
/analysis/h1/set 21 100 0 90    # Fresnel reflection angle
/analysis/h1/set 22 100 0 90    # total internal reflection angle
/analysis/h1/set 24 100 0 90    # absorption angle
/analysis/h1/set 25 100 0 90    # transmitted angle

# ----------------------------
# Electron gun
# ----------------------------
/gun/particle e-
/gun/energy 1 MeV

# Need to change this according to the tile
/gun/position -6 0 0 cm
/gun/direction 1 0 0

/run/printProgress 100
/run/beamOn 1